window.commonWordHide = [ "you", "i", "the", "to", "a", "and", "of", "it",
		"that", "in", "is", "me", "my", "i'm", "on", "what", "with", "have",
		"this", "for", "not", "your", "we", "no", "it's", "do", "was", "don't",
		"oh", "know", "just", "be", "so", "are", "but", "you're", "all",
		"like", "if", "about", "well", "okay", "right", "out", "get", "can",
		"he", "go", "at", "that's", "up", "yeah", "how", "one", "sheldon",
		"want", "going", "her", "why", "here", "think", "an", "now", "good",
		"leonard", "did", "when", "really", "got", "would", "she", "as", "him",
		"there", "come", "see", "by", "hey", "say", "they", "from", "time",
		"his", "little", "can't", "penny", "look", "gonna", "we're", "then",
		"could", "our", "were", "or", "yes", "who", "sorry", "back", "i'll",
		"font", "make", "had", "didn't", "some", "he's", "because", "take",
		"uh", "tell", "been", "i've", "too", "will", "us", "what's", "need",
		"great", "sure", "more", "big", "should", "something", "night", "guys",
		"thank", "mean", "them", "way", "doing", "where", "never", "wait",
		"there's", "two", "let", "has", "maybe", "am", "over", "off", "howard",
		"work", "let's", "talk", "fine", "people", "said", "love", "into",
		"down", "thing", "very", "she's", "amy", "only", "kind", "much",
		"even", "first", "does", "thought", "any", "give", "i'd", "nice",
		"doesn't", "put", "please", "other", "new", "still" ];