window.commonWordHide = [ "you", "i", "the", "to", "a", "and", "of", "it",
		"that", "in", "is", "me", "my", "i'm", "on", "what", "with", "have",
		"this", "for", "not", "your", "we", "no", "it's", "do", "was", "don't",
		"oh", "know", "just", "be", "so", "are", "but", "you're", "all",
		"like", "if", "about", "well", "okay", "right", "out", "get", "can",
		"he", "go", "at", "that's", "up", "yeah", "how", "one", "sheldon",
		"want", "going", "her", "why", "here", "think", "an", "now", "good",
		"leonard", "did", "when", "really", "got", "would", "she", "as", "him",
		"there", "come", "see", "by", "hey", "say", "they", "from", "time",
		"his", "little", "can't", "penny", "look", "gonna", "we're", "then",
		"could", "our", "were", "or", "yes", "who", "sorry", "back", "i'll",
		"font", "make", "had", "didn't", "some", "he's", "because", "take",
		"uh", "tell", "been", "i've", "too", "will", "us", "what's", "need",
		"great", "sure", "more", "big", "should", "something", "night", "guys",
		"thank", "mean", "them", "way", "doing", "where", "never", "wait",
		"there's", "two", "let", "has", "maybe", "am", "over", "off", "howard",
		"work", "let's", "talk", "fine", "people", "said", "love", "into",
		"down", "thing", "very", "she's", "amy", "only", "kind", "much",
		"even", "first", "does", "thought", "any", "give", "i'd", "nice",
		"doesn't", "put", "please", "other", "new", "still", "started", "than",
		"years", "man", "bang", "again", "fun", "things", "feel", "which",
		"believe", "mother", "better", "day", "raj", "ever", "elderman",
		"last", "cool", "might", "before", "course", "help", "being",
		"they're", "made", "god", "date", "guy", "call", "anything", "friends",
		"hello", "always", "talking", "friend", "science", "isn't", "home",
		"life", "actually", "may", "thanks", "those", "hot", "told", "lot",
		"while", "pretty", "built", "wrong", "girl", "stop", "getting",
		"nothing", "bernadette", "ask", "guess", "having", "whole", "dr", "hi",
		"began", "find", "three", "around", "bad", "sync", "play", "these",
		"keep", "next", "excuse", "their", "ago", "sex", "hear", "someone",
		"you've", "corrected", "wolowitz", "wouldn't", "long", "cause",
		"after", "try", "went", "point", "problem", "woman", "understand",
		"saying" ];